#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def EvenFibonaccinumbers():
	sum = 0
	Sequence = FibonacciSequence()
	for x in Sequence:
		if x%2 == 0:
			sum+=x
		continue
	return sum


def Fibonacci(n):
    if n < 0:
        print("Incorrect input")
    elif n == 0:
        return 0
    elif n == 1 or n == 2:
        return 1
    else:
        return Fibonacci(n-1) + Fibonacci(n-2)

def FibonacciSequence():
	i=4
	Sequence = [1,1,2]
	while Fibonacci(i) < 4000000:
		Sequence.append(Fibonacci(i))
		i+=1
	return Sequence

print(EvenFibonaccinumbers())
